<?php
/** @var RocketWeb_GoogleBaseFeedGenerator_Block_Adminhtml_Catalog_Taxonomy_Category_Outer $this */
$innerHtml = $this->getHtml();
$values = $this->getValues();
$level = $this->getLevel();
$enabled = $this->getEnabled();
$disabled = $level > 0; //$enabled ? !$enabled : ($values['disabled'] && $level > 0);
// Disabled for now, so it will always open only 1-level category

if (!empty($innerHtml)): ?>
    <ul class="category_list"
        <?php if ($disabled): ?>
        style="display:none"
        <?php endif; ?>>
        <?php echo $innerHtml; ?>
    </ul>
    <script type="text/javascript">
    //<![CDATA[
        var dataElements = $$('#categories input.input-text');
        for(var i=0; i<dataElements.length;i++){
            Event.observe(dataElements[i], 'change', $("categories").setHasChanges.bind($("categories")));
        }
        var spanElements = $$('#categories span.status');
        for(var i=0; i<spanElements.length;i++){
            Event.observe(spanElements[i], 'click', $("categories").setHasChanges.bind($("categories")));
        }
        //]]>
    </script>
<?php endif; ?>
