<link href='http://fonts.googleapis.com/css?family=Molengo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Tenor+Sans' rel='stylesheet' type='text/css'>
<div class="cms-heading-container">
    <div class="container">
        <div class="page-title">
            <h1><?php echo $this->getLayout()->getBlock('head')->getTitle();?></h1>
        </div>
        <div class="cms-description">
            <div class="cms-border-top"></div>
            <div class="desc-short">
                Zonda is a premiun magento theme
            </div>
            <div class="desc-content">
                With advanced admin module. It's extremely customizable, easy to use and fully responsive.
            </div>
        </div>
    </div>
</div>
